{% set name = "foxes-opt" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/foxes-opt/archive/v{{ version }}.tar.gz
  sha256: c62beae1172a439304f4b07222b22e133bde7b88365d9e8f6c62eafc91f791e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - foxes >=0.7.4
    - iwopy >=0.2.2
    - pymoo >=0.6

test:
  imports:
    - foxes
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/foxes-opt
  summary: Wind farm optimization functionality for foxes
  description: |
    This package provides optimization functionality for the
    wind farm and wake modelling package foxes. It is based
    on the optimization interface package iwopy, and enables the
    user to run fast vectorized and flexible optimizations of 
    wind farm layouts, wind farm control parameters, or any other
    set of related model parameters.
  license: MIT
  license_file: LICENSE
  doc_url: https://fraunhoferiwes.github.io/foxes-opt/index.html
  dev_url: https://github.com/FraunhoferIWES/foxes-opt

extra:
  recipe-maintainers:
    - SchmJo
