{% set name = "foxes-opt" %}
{% set version = "0.6" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/foxes-opt/archive/v{{ version }}.tar.gz
  sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - foxes >=1.5
    - iwopy >=0.3.1
    - pymoo >=0.6
    - netcdf4 >=2023.9
    - h5netcdf >=1.0

test:
  imports:
    - foxes_opt
  requires:
    - python {{ python_min }}
    - pip
    - pytest >=0.7
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/foxes-opt
  summary: Wind farm optimization functionality for foxes
  description: |
    This package provides optimization functionality for the
    wind farm and wake modelling package foxes. It is based
    on the optimization interface package iwopy, and enables the
    user to run fast vectorized and flexible optimizations of 
    wind farm layouts, wind farm control parameters, or any other
    set of related model parameters.
  license: MIT
  license_file: LICENSE
  doc_url: https://fraunhoferiwes.github.io/foxes-opt/index.html
  dev_url: https://github.com/FraunhoferIWES/foxes-opt

extra:
  recipe-maintainers:
    - SchmJo
